### PR TITLE
Fixing the same stupid compressor dupe that 3 other forks have fixed…

### PR DESCRIPTION
**Pull request by SpoilersMC**
…but actually making a pull request this time.
hopefully if this can get pushed to curseforge it'll make someone's life a little easier.
especially for those of us who cant let go of the past; 1.7.10 forever.
@Morpheus1101 Commits on May 26, 2017
@JinXiuying Commits on Nov 26, 2019
@evernife Commits on Dec 9, 2019

### CODE REVIEW

**Comment by Morpheus1101** [comment]
I have nothing to do with the 1.7.10 Branch of this mod only 1.10+

**Comment by SpitefulFox** [comment]
Weird.  I thought I had fixed that already. Thanks.

**Comment by SpitefulFox** [comment]
Wait... I'm not finding a dupe bug when I shift click.  What's the exact thing you gotta do to make it happen?

**Comment by SpoilersMC** [comment]
yeah apologies for the mention morpheus I was just making sure to cite the other forks with the same fix.
and for spiteful, just in case you didnt find the dupe yet, its this:
Avaritia dupe
JinXiuying's commit on the gregtech fork also had a step-by-step in the description of the commit.

And wow, I was very much not expecting such quick action, a million thanks.

**Comment by SpitefulFox** [comment]
Cool. Thanks for showing me.  I remember finding a dupe glitch involving shift click years ago and couldn't remember how it worked or if I had fixed it.  I'll get the fixed version uploaded to curseforge as soon as possible. Also, there's a GregTech fork? o_o

**Comment by SpitefulFox** [comment]
... or not because apparently compiling for 1.7.10 got its bridge burned at some point.

**Comment by SpoilersMC** [comment]
yeah you gotta change the maven urls in the build.gradle and point gradle-wrapper.properties to a newer gradle version
I used gradle 2.6 when I compiled.
[build.gradle.txt](https://github.com/SpitefulFox/Avaritia/files/5119664/build.gradle.txt)
this is the build.gradle I compiled on, the only changes from yours are updated forge version and corrected maven URLs

**Pull request merged**
