### PR TITLE
improve some textures

### PR DESCRIPTION
**Pull request by RCXcrafter**
Finished the axe and alternate shovel texture and improved singularity texture ever so slightly.

### CODE REVIEW

**Comment by SpitefulFox** [comment]
What year is it?! How long have I been sitting on this? o_o

**Comment by SpitefulFox** [comment]
What are the differences in the singularity texture?

**Comment by RCXcrafter** [comment]
the last frame in the background texture and the first frame in the overlay texture looked a bit "clunky" to me so those are different.
image

**Comment by SpitefulFox** [comment]
Can't say when I'll release a new update, but thanks. x3 Have you submitted this to Morpheus' version as well?

**Pull request merged**
